# Python code generated by CAIT's Visual Programming Interface

import cait.essentials

person = None
facemesh = None
emotions = None

def setup():
    cait.essentials.initialize_component('vision', processor='oakd', mode=[["add_rgb_cam_node", 640, 360], ["add_rgb_cam_preview_node"],["add_nn_node_pipeline", "face_detection", "face-detection-retail-0004_openvino_2021.2_6shave.blob", 300, 300],["add_nn_node", "face_landmarks", "landmarks-regression-retail-0009_openvino_2021.2_6shave.blob", 48, 48], ["add_nn_node", "face_features", "mobilefacenet.blob", 112, 112],["add_nn_node", "facemesh", "facemesh_sh6.blob", 192, 192],["add_nn_node", "face_emotions", "emotions-recognition-retail-0003.blob", 64, 64]])
    
def main():
    global person, facemesh, emotions
    while True:
        person = cait.essentials.recognize_face()
        cait.essentials.draw_recognized_face(person)
        facemesh = cait.essentials.facemesh_estimation()
        cait.essentials.draw_estimated_facemesh(facemesh)
        emotions = cait.essentials.face_emotions_estimation()
        cait.essentials.draw_estimated_emotions(emotions)

if __name__ == "__main__":
    setup()
    main()