# Python code generated by CAIT's Visual Programming Interface

import cait.essentials

def setup():
    cait.essentials.initialize_component('vision', processor='oakd', mode=[["add_rgb_cam_node", 640, 360], ["add_rgb_cam_preview_node"],["add_stereo_cam_node", False], ["add_stereo_frame_node"]])
    
def main():
    cait.essentials.enable_drawing_mode('Depth Mode')

if __name__ == "__main__":
    setup()
    main()