# Python code generated by CAIT's Visual Programming Interface

import cait.essentials

def setup():
    cait.essentials.initialize_component('vision', processor='oakd', mode=[["add_rgb_cam_node", 640, 360], ["add_rgb_cam_preview_node"]])
    
def main():

if __name__ == "__main__":
    setup()
    main()