# Python code generated by CAIT's Visual Programming Interface

import cait.essentials

face = None

def setup():
    cait.essentials.initialize_component('vision', processor='oakd', mode=[["add_rgb_cam_node", 640, 360], ["add_rgb_cam_preview_node"],["add_nn_node_pipeline", "face_detection", "face-detection-retail-0004_openvino_2021.2_6shave.blob", 300, 300]])
    
def main():
    global face
    while True:
        face = cait.essentials.detect_face(processor='oakd')
        cait.essentials.draw_detected_face(face)

if __name__ == "__main__":
    setup()
    main()