# Python code generated by CAIT's Visual Programming Interface

import cait.essentials

person = None

def setup():
    cait.essentials.initialize_component('vision', processor='oakd', mode=[["add_rgb_cam_node", 640, 360], ["add_rgb_cam_preview_node"],["add_nn_node_pipeline", "face_detection", "face-detection-retail-0004_openvino_2021.2_6shave.blob", 300, 300],["add_nn_node", "face_landmarks", "landmarks-regression-retail-0009_openvino_2021.2_6shave.blob", 48, 48], ["add_nn_node", "face_features", "mobilefacenet.blob", 112, 112]])
    
def main():
    global person
    while True:
        person = cait.essentials.recognize_face()
        cait.essentials.draw_recognized_face(person)

if __name__ == "__main__":
    setup()
    main()