# Python code generated by CAIT's Visual Programming Interface

import cait.essentials

def setup():
    cait.essentials.initialize_component('smart_home')
    
def main():
    cait.essentials.control_light('light.main_lights', 'turn_on')
    cait.essentials.control_media_player('media_player.office_speaker', 'media_play')

if __name__ == "__main__":
    setup()
    main()